#!/usr/bin/env bash

dry="0"

log() {
    if [[ $dry == "1" ]]; then
        echo "[DRY_RUN]: $1"
    else
        echo "$1"
    fi
}

if [ -z "$XDG_CONFIG_HOME" ]; then
    log "no xdg config home"
    log "using ~/.config"
    XDG_CONFIG_HOME=$HOME/.config
fi

if [ -z "$DEV_ENV" ]; then
    log "no DEV_ENV env var is present"
    log "using ~/dev"
    DEV_ENV=$HOME/dev
fi

if [[ $1 == "--dry" ]]; then
    dry="1"
fi

log "env: $DEV_ENV"

update_files() {
    log "copying over files from: $1"
    pushd $1 &> /dev/null
    (
        configs=`find . -mindepth 1 -maxdepth 1 -type d`
        for c in $configs; do
            directory=${2%/}/${c#./}
            log " removing: rm -rf $directory"

            if [[ $dry == "0" ]]; then
                rm -rf $directory
            fi
            
            log "   copying env: cp -r $c $2"
            if [[ $dry == "0" ]]; then
                cp -r ./$c $2
            fi
        done
    )
    popd &> /dev/null
}

copy() {
    log "removing: $2"
    if [[ $dry == "0" ]]; then
        rm $2
    fi
    log " copying: $1 to $2"
    if [[ $dry == "0" ]]; then
        cp $1 $2
    fi
}

mkdir -p $HOME/.local/scripts

update_files $DEV_ENV/env/.config $XDG_CONFIG_HOME

copy $DEV_ENV/tmux-sessionizer/tmux-sessionizer $HOME/.local/scripts/tmux-sessionizer
copy $DEV_ENV/env/.zsh_profile $HOME/.zsh_profile
copy $DEV_ENV/env/.zshrc $HOME/.zshrc
copy $DEV_ENV/env/.tmux.conf $HOME/.tmux.conf
copy $DEV_ENV/dev-env $HOME/.local/scripts/dev-env
