#!/usr/bin/env bash

# install homebrew if it doesn't exist
if ! command -v brew &> /dev/null; then
  echo "Installing Homebrew"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
    echo "Homebrew already installed"
fi

if ! command -v git &> /dev/null; then
  echo "Installing git"
  brew install git
else
    echo "Git already installed"
fi

if [ ! -d "$HOME/Projects" ]; then
  echo "Creating Projects directory"
  mkdir $HOME/Projects
else
    echo "Projects directory already exists"
fi

git clone https://github.com/guanguer/dev $HOME/Projects/dev

pushd $HOME/Projects/dev
./run
popd
